ALTER TABLE users ADD COLUMN origin TEXT NOT NULL DEFAULT 'YYT';
ALTER TABLE users ADD COLUMN destination TEXT NOT NULL DEFAULT 'DEL';
ALTER TABLE users ADD COLUMN hubs TEXT NOT NULL DEFAULT 'YYZ,YUL';
