ALTER TABLE users ADD COLUMN depart_start TEXT NOT NULL DEFAULT '2026-11-18';
ALTER TABLE users ADD COLUMN depart_end TEXT NOT NULL DEFAULT '2026-12-02';
ALTER TABLE users ADD COLUMN return_start TEXT NOT NULL DEFAULT '2026-12-30';
ALTER TABLE users ADD COLUMN return_end TEXT NOT NULL DEFAULT '2027-01-13';
ALTER TABLE users ADD COLUMN trip_min_days INTEGER NOT NULL DEFAULT 28;
